spring:
  mail:
    host: smtp.gmail.com
    username: elvinaliyevinfo@gmail.com
    password: gxzhxbljjjfclisz
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
