-- insert into stock table
INSERT INTO `STOCKS` (NAME,PRICE) VALUES ('10X CAPITAL VENTURE ACQUISITION', 9.98);
INSERT INTO `STOCKS` (NAME,PRICE) VALUES ('3D SYSTEMS CORP', 7.76);
INSERT INTO `STOCKS` (NAME,PRICE) VALUES ('3M COMPANY', 130.1);
INSERT INTO `STOCKS` (NAME,PRICE) VALUES ('8X8 INC', 5.76);
INSERT INTO `STOCKS` (NAME,PRICE) VALUES ('A.K.A. BRANDS HOLDING', 2.94);
INSERT INTO `STOCKS` (NAME,PRICE) VALUES ('A.O. SMITH CORP', 54.13);
INSERT INTO `STOCKS` (NAME,PRICE) VALUES ('ACUSHNET HOLDINGS', 39.78);
INSERT INTO `STOCKS` (NAME,PRICE) VALUES ('ACCENTURE PLC CLASS A', 14.59);
INSERT INTO `STOCKS` (NAME,PRICE) VALUES ('ADC THERAPEUTICS SA', 27.42);
